# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionnota',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencia', to='edu.CompetenciaArea', verbose_name='área'),
        ),
        migrations.AlterField(
            model_name='evaluacionalumno',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicador', to='edu.Nivel'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel', to='edu.Competencia'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set([('numero', 'indicador')]),
        ),
    ]
