# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20161123_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
    ]
