# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20161124_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionindicador',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='edu.Evaluacion'),
        ),
        migrations.AlterField(
            model_name='evaluacionindicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='edu.Indicador'),
        ),
    ]
