# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20161124_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='creador_por',
            new_name='creada_por',
        ),
    ]
